-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  industry text,
  settings jsonb DEFAULT '{}'::jsonb,
  subscription_status text DEFAULT 'active'::text,
  subscription_tier text DEFAULT 'standard'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stripe_customer_id text,
  stripe_connect_account_id text,
  stripe_connect_onboarded_at timestamp with time zone,
  signup_product text,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  tenant_id uuid,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'admin'::text,
  avatar_url text,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.workers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  phone text NOT NULL,
  email text,
  avatar_url text,
  worker_type USER-DEFINED NOT NULL DEFAULT 'company_subcontractor'::worker_type,
  primary_tenant_id uuid,
  home_postcode text,
  home_lat numeric,
  home_lng numeric,
  service_radius_km integer DEFAULT 50,
  skills jsonb DEFAULT '[]'::jsonb,
  certifications jsonb DEFAULT '[]'::jsonb,
  status USER-DEFINED DEFAULT 'available'::worker_status,
  total_jobs_completed integer DEFAULT 0,
  average_rating numeric,
  total_reviews integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expo_push_token text,
  invite_status text DEFAULT 'pending'::text,
  CONSTRAINT workers_pkey PRIMARY KEY (id),
  CONSTRAINT workers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workers_primary_tenant_id_fkey FOREIGN KEY (primary_tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.worker_tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid,
  tenant_id uuid,
  status text DEFAULT 'active'::text,
  is_primary boolean DEFAULT false,
  commission_rate numeric,
  hourly_rate numeric,
  jobs_completed integer DEFAULT 0,
  average_rating numeric,
  added_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  exclude_from_auto_assign boolean NOT NULL DEFAULT false,
  CONSTRAINT worker_tenants_pkey PRIMARY KEY (id),
  CONSTRAINT worker_tenants_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT worker_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  name text NOT NULL,
  contact_person text,
  email text,
  phone text,
  type USER-DEFINED NOT NULL DEFAULT 'individual'::customer_type,
  company_name text,
  billing_address text,
  portal_last_accessed_at timestamp with time zone,
  total_jobs integer DEFAULT 0,
  last_job_date date,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  import_column_mapping jsonb,
  import_value_transforms jsonb NOT NULL DEFAULT '{}'::jsonb,
  import_expected_headers ARRAY NOT NULL DEFAULT '{}'::text[],
  import_mapping_updated_at timestamp with time zone,
  worker_visible_fields jsonb,
  phone_e164 text,
  preferred_channel text CHECK (preferred_channel IS NULL OR (preferred_channel = ANY (ARRAY['whatsapp'::text, 'sms'::text, 'email'::text, 'none'::text]))),
  messaging_opt_in_at timestamp with time zone,
  messaging_opt_out_at timestamp with time zone,
  whatsapp_opt_in_at timestamp with time zone,
  whatsapp_capable boolean,
  payment_terms text NOT NULL DEFAULT 'on_the_day'::text CHECK (payment_terms = ANY (ARRAY['on_the_day'::text, 'invoice'::text, 'monthly_invoice'::text])),
  bank_reference_hint text,
  access_notes text,
  pay_link_token text,
  visit_reminders boolean,
  payment_chasers boolean,
  payment_thanks boolean,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.import_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  source_name text NOT NULL,
  source_identifier text,
  column_mapping jsonb NOT NULL,
  mapped_by text DEFAULT 'manual'::text,
  ai_confidence numeric,
  last_used_at timestamp with time zone,
  times_used integer DEFAULT 0,
  required_columns ARRAY,
  default_values jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  customer_id uuid,
  value_transforms jsonb NOT NULL DEFAULT '{}'::jsonb,
  grouping_columns jsonb,
  CONSTRAINT import_sources_pkey PRIMARY KEY (id),
  CONSTRAINT import_sources_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT import_sources_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  reference_number text NOT NULL,
  customer_id uuid,
  assigned_worker_id uuid,
  import_source_id uuid,
  address text NOT NULL,
  postcode text NOT NULL,
  lat numeric,
  lng numeric,
  job_description text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::job_status,
  priority USER-DEFINED NOT NULL DEFAULT 'normal'::job_priority,
  scheduled_date date,
  scheduled_time time without time zone,
  estimated_duration_minutes integer,
  started_at timestamp with time zone,
  arrived_at timestamp with time zone,
  completed_at timestamp with time zone,
  industry_data jsonb DEFAULT '{}'::jsonb,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  quoted_amount numeric,
  final_amount numeric,
  completion_notes text,
  customer_signature_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  required_skills jsonb DEFAULT '[]'::jsonb,
  auto_assign_failure_reason text,
  network_dispatch_id uuid,
  job_length text CHECK (job_length = ANY (ARRAY['half_day'::text, 'full_day'::text])),
  source_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_fields_text text DEFAULT (source_fields)::text,
  end_time time without time zone,
  decline_reason text,
  job_group_id uuid,
  service_agreement_id uuid,
  agreement_occurrence_date date,
  route_position integer,
  skip_reason text CHECK (skip_reason IS NULL OR (skip_reason = ANY (ARRAY['no_access'::text, 'weather'::text, 'customer_declined'::text, 'customer_away'::text, 'agreement_paused'::text, 'agreement_ended'::text, 'other'::text, 'trader_unavailable'::text]))),
  payment_status text CHECK (payment_status IS NULL OR (payment_status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text, 'waived'::text, 'invoiced'::text]))),
  customer_confirmation_status text CHECK (customer_confirmation_status IS NULL OR (customer_confirmation_status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'declined'::text, 'rescheduled'::text, 'replied'::text]))),
  customer_requested_date date,
  customer_reply_at timestamp with time zone,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT jobs_assigned_worker_id_fkey FOREIGN KEY (assigned_worker_id) REFERENCES public.workers(id),
  CONSTRAINT jobs_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id),
  CONSTRAINT jobs_network_dispatch_id_fkey FOREIGN KEY (network_dispatch_id) REFERENCES public.network_job_dispatches(id),
  CONSTRAINT jobs_job_group_id_fkey FOREIGN KEY (job_group_id) REFERENCES public.job_groups(id),
  CONSTRAINT jobs_service_agreement_id_fkey FOREIGN KEY (service_agreement_id) REFERENCES public.service_agreements(id)
);
CREATE TABLE public.job_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size_bytes integer,
  attachment_type text NOT NULL DEFAULT 'other'::text,
  caption text,
  uploaded_by_worker_id uuid,
  uploaded_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT job_attachments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_attachments_uploaded_by_worker_id_fkey FOREIGN KEY (uploaded_by_worker_id) REFERENCES public.workers(id),
  CONSTRAINT job_attachments_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.import_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  import_source_id uuid,
  file_name text NOT NULL,
  file_size_bytes integer,
  rows_total integer NOT NULL,
  rows_imported integer NOT NULL,
  rows_failed integer DEFAULT 0,
  job_ids ARRAY,
  errors jsonb DEFAULT '[]'::jsonb,
  imported_by_user_id uuid,
  started_at timestamp with time zone NOT NULL,
  completed_at timestamp with time zone,
  duration_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT import_history_pkey PRIMARY KEY (id),
  CONSTRAINT import_history_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT import_history_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id),
  CONSTRAINT import_history_imported_by_user_id_fkey FOREIGN KEY (imported_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.job_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  from_status USER-DEFINED,
  to_status USER-DEFINED NOT NULL,
  changed_by_user_id uuid,
  changed_by_worker_id uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT job_status_history_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_status_history_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT job_status_history_changed_by_worker_id_fkey FOREIGN KEY (changed_by_worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  recipient_type text NOT NULL,
  recipient_id uuid,
  recipient_email text,
  recipient_phone text,
  type text NOT NULL,
  channel text NOT NULL,
  subject text,
  body text NOT NULL,
  job_id uuid,
  status text DEFAULT 'pending'::text,
  sent_at timestamp with time zone,
  failed_reason text,
  provider text,
  provider_message_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT notifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.ai_interactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  interaction_type text NOT NULL CHECK (interaction_type = ANY (ARRAY['skill_detection'::text, 'quote_generation'::text, 'column_mapping'::text, 'worker_interview_parsing'::text, 'value_transformation'::text, 'date_parsing'::text, 'description_summary'::text, 'row_extraction'::text, 'customer_row_extraction'::text, 'message_classification'::text, 'receipt_extraction'::text, 'invoice_drafting'::text])),
  input_prompt text NOT NULL,
  input_data jsonb NOT NULL,
  ai_response text NOT NULL,
  parsed_output jsonb,
  model text NOT NULL,
  provider text NOT NULL DEFAULT 'anthropic'::text,
  tokens_input integer,
  tokens_output integer,
  tokens_total integer,
  latency_ms integer,
  cost_usd numeric,
  user_edited boolean DEFAULT false,
  user_rating integer CHECK (user_rating >= 1 AND user_rating <= 5),
  accepted boolean DEFAULT true,
  edit_details jsonb,
  actual_outcome jsonb,
  accuracy_score numeric,
  job_id uuid,
  worker_id uuid,
  import_source_id uuid,
  quote_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_agent text,
  ip_address inet,
  environment text DEFAULT 'production'::text CHECK (environment = ANY (ARRAY['production'::text, 'staging'::text, 'development'::text])),
  CONSTRAINT ai_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_interactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT ai_interactions_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT ai_interactions_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT ai_interactions_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id)
);
CREATE TABLE public.ai_training_datasets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  dataset_type text NOT NULL CHECK (dataset_type = ANY (ARRAY['skill_detection'::text, 'quote_estimation'::text, 'pricing_optimization'::text, 'worker_matching'::text, 'full_export'::text])),
  version text NOT NULL,
  examples_count integer NOT NULL,
  training_split numeric DEFAULT 0.80,
  validation_split numeric DEFAULT 0.10,
  test_split numeric DEFAULT 0.10,
  quality_score numeric,
  human_reviewed_count integer DEFAULT 0,
  accuracy_threshold numeric,
  file_path text,
  file_size_bytes bigint,
  file_format text DEFAULT 'jsonl'::text CHECK (file_format = ANY (ARRAY['jsonl'::text, 'csv'::text, 'parquet'::text])),
  trained_model_id uuid,
  training_started_at timestamp with time zone,
  training_completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  notes text,
  tags ARRAY,
  CONSTRAINT ai_training_datasets_pkey PRIMARY KEY (id),
  CONSTRAINT ai_training_datasets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.ai_model_performance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  model_type text NOT NULL CHECK (model_type = ANY (ARRAY['claude_api'::text, 'custom_skill_classifier'::text, 'custom_quote_estimator'::text, 'hybrid'::text])),
  model_version text NOT NULL,
  total_predictions integer DEFAULT 0,
  correct_predictions integer DEFAULT 0,
  accuracy numeric,
  precision_score numeric,
  recall_score numeric,
  f1_score numeric,
  total_cost_usd numeric,
  avg_cost_per_prediction numeric,
  avg_latency_ms integer,
  avg_user_rating numeric,
  edit_rate numeric,
  acceptance_rate numeric,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT ai_model_performance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenant_network_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id_a uuid NOT NULL,
  tenant_id_b uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'rejected'::text, 'revoked'::text])),
  invited_by_tenant_id uuid NOT NULL,
  invited_by_user_id uuid,
  invite_email text,
  message text,
  trade_types ARRAY DEFAULT '{}'::text[],
  coverage_area_centre point,
  coverage_radius_miles integer DEFAULT 50,
  responded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_network_connections_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_network_connections_tenant_id_a_fkey FOREIGN KEY (tenant_id_a) REFERENCES public.tenants(id),
  CONSTRAINT tenant_network_connections_tenant_id_b_fkey FOREIGN KEY (tenant_id_b) REFERENCES public.tenants(id),
  CONSTRAINT tenant_network_connections_invited_by_tenant_id_fkey FOREIGN KEY (invited_by_tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tenant_network_connections_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.network_job_dispatches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  connection_id uuid NOT NULL,
  originating_tenant_id uuid NOT NULL,
  receiving_tenant_id uuid NOT NULL,
  canonical_job_id uuid NOT NULL,
  originating_reference_number text,
  originating_customer_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_job_dispatches_pkey PRIMARY KEY (id),
  CONSTRAINT network_job_dispatches_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES public.tenant_network_connections(id),
  CONSTRAINT network_job_dispatches_originating_tenant_id_fkey FOREIGN KEY (originating_tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT network_job_dispatches_receiving_tenant_id_fkey FOREIGN KEY (receiving_tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT network_job_dispatches_canonical_job_id_fkey FOREIGN KEY (canonical_job_id) REFERENCES public.jobs(id),
  CONSTRAINT network_job_dispatches_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.customer_portal_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_portal_users_pkey PRIMARY KEY (id),
  CONSTRAINT customer_portal_users_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_portal_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tenant_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  key text NOT NULL,
  label text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tenant_skills_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_skills_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.worker_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  worker_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  email text NOT NULL,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '48:00:00'::interval),
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT worker_invites_pkey PRIMARY KEY (id),
  CONSTRAINT worker_invites_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT worker_invites_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.customer_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  customer_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  email text NOT NULL,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '48:00:00'::interval),
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_invites_pkey PRIMARY KEY (id),
  CONSTRAINT customer_invites_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_invites_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.password_resets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  user_id uuid NOT NULL,
  email text NOT NULL,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '02:00:00'::interval),
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.widget_clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  business_name text NOT NULL,
  trade text NOT NULL,
  service_area text NOT NULL,
  pricing_context text NOT NULL DEFAULT ''::text,
  business_context text NOT NULL DEFAULT ''::text,
  greeting text NOT NULL DEFAULT 'Hi! What type of job do you need help with today?'::text,
  primary_colour text NOT NULL DEFAULT '#0C66E4'::text,
  notification_email text NOT NULL,
  allowed_domains ARRAY NOT NULL DEFAULT '{}'::text[],
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT widget_clients_pkey PRIMARY KEY (id),
  CONSTRAINT widget_clients_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.widget_conversations (
  id uuid NOT NULL,
  client_id uuid NOT NULL,
  tenant_id uuid,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT widget_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT widget_conversations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.widget_clients(id),
  CONSTRAINT widget_conversations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.widget_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  conversation_id uuid,
  tenant_id uuid,
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  job_description text NOT NULL DEFAULT ''::text,
  quote_given text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'new'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT widget_leads_pkey PRIMARY KEY (id),
  CONSTRAINT widget_leads_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.widget_clients(id),
  CONSTRAINT widget_leads_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.widget_conversations(id),
  CONSTRAINT widget_leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  source text NOT NULL DEFAULT 'chatbot'::text,
  name text NOT NULL,
  phone text,
  email text,
  job_description text NOT NULL DEFAULT ''::text,
  quote_given text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'new'::text,
  notes text,
  widget_conversation_id uuid,
  source_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  converted_customer_id uuid,
  converted_job_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_widget_conversation_id_fkey FOREIGN KEY (widget_conversation_id) REFERENCES public.widget_conversations(id),
  CONSTRAINT leads_converted_customer_id_fkey FOREIGN KEY (converted_customer_id) REFERENCES public.customers(id),
  CONSTRAINT leads_converted_job_id_fkey FOREIGN KEY (converted_job_id) REFERENCES public.jobs(id),
  CONSTRAINT leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.automation_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  service_key text NOT NULL,
  metric_type text NOT NULL,
  value numeric NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  occurred_at timestamp with time zone DEFAULT now(),
  CONSTRAINT automation_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT automation_metrics_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.job_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  label text NOT NULL,
  import_history_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_groups_pkey PRIMARY KEY (id),
  CONSTRAINT job_groups_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT job_groups_import_history_id_fkey FOREIGN KEY (import_history_id) REFERENCES public.import_history(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  product text NOT NULL CHECK (product = ANY (ARRAY['lite'::text, 'rounds'::text, 'starter'::text, 'growth'::text, 'pro'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['trialing'::text, 'active'::text, 'past_due'::text, 'canceled'::text, 'unpaid'::text, 'incomplete'::text, 'incomplete_expired'::text, 'paused'::text, 'manual'::text])),
  source text NOT NULL DEFAULT 'stripe'::text CHECK (source = ANY (ARRAY['stripe'::text, 'manual'::text])),
  stripe_customer_id text,
  stripe_subscription_id text UNIQUE,
  stripe_price_id text,
  trial_ends_at timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  canceled_at timestamp with time zone,
  seats integer NOT NULL DEFAULT 1 CHECK (seats >= 1),
  granted_by_user_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT subscriptions_granted_by_user_id_fkey FOREIGN KEY (granted_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.signup_intents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  email text NOT NULL,
  product text NOT NULL CHECK (product = ANY (ARRAY['lite'::text, 'rounds'::text])),
  business_name text NOT NULL,
  full_name text NOT NULL,
  phone text,
  postcode text,
  trade text,
  stripe_customer_id text,
  stripe_checkout_session_id text UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'provisioned'::text, 'abandoned'::text])),
  tenant_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  provisioned_at timestamp with time zone,
  CONSTRAINT signup_intents_pkey PRIMARY KEY (id),
  CONSTRAINT signup_intents_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT signup_intents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.stripe_events (
  id text NOT NULL,
  type text NOT NULL,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  error text,
  CONSTRAINT stripe_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  default_price numeric NOT NULL DEFAULT 0 CHECK (default_price >= 0::numeric),
  default_duration_minutes integer NOT NULL DEFAULT 30 CHECK (default_duration_minutes > 0),
  default_frequency_days integer CHECK (default_frequency_days IS NULL OR default_frequency_days >= 1 AND default_frequency_days <= 365),
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT service_catalog_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.service_agreements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  service_catalog_id uuid,
  title text NOT NULL,
  address text NOT NULL,
  postcode text NOT NULL,
  lat numeric,
  lng numeric,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  duration_minutes integer NOT NULL DEFAULT 30 CHECK (duration_minutes > 0),
  frequency_days integer NOT NULL CHECK (frequency_days >= 1 AND frequency_days <= 365),
  anchor_date date NOT NULL,
  preferred_weekday smallint CHECK (preferred_weekday IS NULL OR preferred_weekday >= 1 AND preferred_weekday <= 7),
  preferred_time time without time zone,
  schedule_mode text NOT NULL DEFAULT 'fixed'::text CHECK (schedule_mode = ANY (ARRAY['fixed'::text, 'after_completion'::text])),
  next_due_date date NOT NULL,
  last_generated_at timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'ended'::text])),
  paused_until date,
  ended_at timestamp with time zone,
  assigned_worker_id uuid,
  default_payment_method text CHECK (default_payment_method IS NULL OR (default_payment_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'card'::text, 'cheque'::text, 'other'::text]))),
  reminder_enabled boolean NOT NULL DEFAULT true,
  access_notes text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_agreements_pkey PRIMARY KEY (id),
  CONSTRAINT service_agreements_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT service_agreements_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT service_agreements_service_catalog_id_fkey FOREIGN KEY (service_catalog_id) REFERENCES public.service_catalog(id),
  CONSTRAINT service_agreements_assigned_worker_id_fkey FOREIGN KEY (assigned_worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.service_preset_groups (
  key text NOT NULL,
  label text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT service_preset_groups_pkey PRIMARY KEY (key)
);
CREATE TABLE public.service_presets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_key text NOT NULL,
  name text NOT NULL,
  default_price numeric NOT NULL CHECK (default_price >= 0::numeric),
  default_duration_minutes integer NOT NULL DEFAULT 30 CHECK (default_duration_minutes > 0),
  default_frequency_days integer CHECK (default_frequency_days IS NULL OR default_frequency_days >= 1 AND default_frequency_days <= 365),
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT service_presets_pkey PRIMARY KEY (id),
  CONSTRAINT service_presets_group_key_fkey FOREIGN KEY (group_key) REFERENCES public.service_preset_groups(key)
);
CREATE TABLE public.tenant_payment_settings (
  tenant_id uuid NOT NULL,
  bank_account_name text CHECK (bank_account_name IS NULL OR char_length(btrim(bank_account_name)) >= 1 AND char_length(btrim(bank_account_name)) <= 70),
  bank_sort_code text CHECK (bank_sort_code IS NULL OR bank_sort_code ~ '^[0-9]{6}$'::text),
  bank_account_number text CHECK (bank_account_number IS NULL OR bank_account_number ~ '^[0-9]{8}$'::text),
  vat_registered boolean NOT NULL DEFAULT false,
  vat_number text,
  vat_rate_percent numeric NOT NULL DEFAULT 20 CHECK (vat_rate_percent >= 0::numeric AND vat_rate_percent <= 100::numeric),
  invoice_due_days integer NOT NULL DEFAULT 14 CHECK (invoice_due_days >= 0 AND invoice_due_days <= 90),
  invoice_prefix text NOT NULL DEFAULT 'INV'::text CHECK (invoice_prefix ~ '^[A-Z0-9]{1,10}$'::text),
  next_invoice_seq integer NOT NULL DEFAULT 1 CHECK (next_invoice_seq >= 1),
  invoice_footer text CHECK (invoice_footer IS NULL OR char_length(invoice_footer) <= 500),
  stripe_connect_charges_enabled boolean NOT NULL DEFAULT false,
  stripe_connect_payouts_enabled boolean NOT NULL DEFAULT false,
  stripe_connect_details_submitted boolean NOT NULL DEFAULT false,
  stripe_connect_requirements_due ARRAY NOT NULL DEFAULT '{}'::text[],
  stripe_connect_disabled_reason text,
  stripe_connect_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_payment_settings_pkey PRIMARY KEY (tenant_id),
  CONSTRAINT tenant_payment_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric AND amount <= 100000::numeric),
  method text NOT NULL CHECK (method = ANY (ARRAY['cash'::text, 'cheque'::text, 'bank_transfer'::text, 'card'::text, 'direct_debit'::text, 'pay_by_bank'::text, 'other'::text])),
  source text NOT NULL DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'stripe'::text, 'open_banking'::text, 'gocardless'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'void'::text])),
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  note text CHECK (note IS NULL OR char_length(note) <= 300),
  applies_to_job_id uuid,
  invoice_id uuid,
  recorded_by_user_id uuid,
  client_mutation_id text UNIQUE,
  stripe_payment_intent_id text UNIQUE,
  stripe_checkout_session_id text UNIQUE,
  stripe_charge_id text,
  refunded_amount numeric NOT NULL DEFAULT 0,
  disputed_at timestamp with time zone,
  dispute_status text,
  bank_transaction_id uuid UNIQUE,
  voided_at timestamp with time zone,
  voided_by_user_id uuid,
  void_reason text CHECK (void_reason IS NULL OR char_length(void_reason) <= 300),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  gocardless_payment_id text UNIQUE,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT payments_applies_to_job_id_fkey FOREIGN KEY (applies_to_job_id) REFERENCES public.jobs(id),
  CONSTRAINT payments_recorded_by_user_id_fkey FOREIGN KEY (recorded_by_user_id) REFERENCES public.users(id),
  CONSTRAINT payments_voided_by_user_id_fkey FOREIGN KEY (voided_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  payment_id uuid NOT NULL,
  job_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  charge_id uuid,
  CONSTRAINT payment_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT payment_allocations_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT payment_allocations_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT payment_allocations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT payment_allocations_charge_id_fkey FOREIGN KEY (charge_id) REFERENCES public.customer_charges(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  number text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['visit'::text, 'balance'::text])),
  status text NOT NULL DEFAULT 'issued'::text CHECK (status = ANY (ARRAY['issued'::text, 'void'::text])),
  issue_date date NOT NULL,
  due_date date NOT NULL,
  seller_name text NOT NULL,
  seller_address text,
  seller_phone text,
  seller_email text,
  seller_logo_url text,
  seller_vat_number text,
  bill_to_name text NOT NULL,
  bill_to_company text,
  bill_to_address text,
  bill_to_email text,
  bank_account_name text,
  bank_sort_code text,
  bank_account_number text,
  payment_reference text,
  vat_rate_percent numeric,
  subtotal_net numeric NOT NULL,
  vat_amount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL,
  amount_paid_at_issue numeric NOT NULL DEFAULT 0,
  footer text,
  public_token text NOT NULL UNIQUE,
  sent_at timestamp with time zone,
  sent_to_email text,
  voided_at timestamp with time zone,
  void_reason text CHECK (void_reason IS NULL OR char_length(void_reason) <= 300),
  created_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT invoices_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  job_id uuid,
  service_date date,
  description text NOT NULL,
  address text,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT invoice_lines_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_lines_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_lines_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT invoice_lines_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.message_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  channel text NOT NULL DEFAULT 'sms'::text CHECK (channel = ANY (ARRAY['sms'::text, 'whatsapp'::text])),
  customer_address text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'needs_attention'::text, 'closed'::text])),
  needs_attention_reason text,
  active_job_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  active_set_at timestamp with time zone,
  last_inbound_at timestamp with time zone,
  last_outbound_at timestamp with time zone,
  unread_count integer NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_threads_pkey PRIMARY KEY (id),
  CONSTRAINT message_threads_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT message_threads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  thread_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  channel text NOT NULL DEFAULT 'sms'::text CHECK (channel = ANY (ARRAY['sms'::text, 'whatsapp'::text, 'email'::text])),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['reminder'::text, 'visit_done'::text, 'chaser'::text, 'payment_received'::text, 'visit_change'::text, 'reply_ack'::text, 'inbound'::text, 'dd_invite'::text, 'dd_failed'::text])),
  body text NOT NULL,
  to_address text,
  from_address text,
  job_id uuid,
  job_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  visit_change_id uuid,
  dedupe_key text,
  status text NOT NULL CHECK (status = ANY (ARRAY['held'::text, 'queued'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'skipped'::text, 'received'::text])),
  hold_until timestamp with time zone,
  segments integer CHECK (segments IS NULL OR segments >= 1 AND segments <= 10),
  billed_from text CHECK (billed_from IS NULL OR (billed_from = ANY (ARRAY['allowance'::text, 'pack'::text]))),
  billed_month text,
  provider text NOT NULL DEFAULT 'puresms'::text,
  provider_message_id text,
  provider_status text,
  error text,
  classification text CHECK (classification IS NULL OR (classification = ANY (ARRAY['said_no'::text, 'asked_move'::text, 'question'::text, 'opt_out'::text, 'opt_in'::text, 'other'::text]))),
  classification_confidence numeric,
  requested_date date,
  handled_at timestamp with time zone,
  handled_action text CHECK (handled_action IS NULL OR (handled_action = ANY (ARRAY['skipped'::text, 'kept'::text, 'moved'::text, 'dismissed'::text]))),
  email_fallback_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.message_threads(id),
  CONSTRAINT messages_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT messages_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT messages_visit_change_id_fkey FOREIGN KEY (visit_change_id) REFERENCES public.visit_changes(id)
);
CREATE TABLE public.messaging_opt_outs (
  phone_e164 text NOT NULL,
  opted_out_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'keyword'::text CHECK (source = ANY (ARRAY['keyword'::text, 'provider'::text, 'manual'::text])),
  last_keyword text,
  CONSTRAINT messaging_opt_outs_pkey PRIMARY KEY (phone_e164)
);
CREATE TABLE public.messaging_inbound_limits (
  phone_e164 text NOT NULL,
  window_started_at timestamp with time zone NOT NULL DEFAULT now(),
  count_in_window integer NOT NULL DEFAULT 0 CHECK (count_in_window >= 0),
  blocked_until timestamp with time zone,
  last_autoreply_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messaging_inbound_limits_pkey PRIMARY KEY (phone_e164)
);
CREATE TABLE public.messaging_unrouted_inbound (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  from_address text NOT NULL,
  body text NOT NULL,
  provider text NOT NULL DEFAULT 'puresms'::text,
  provider_message_id text,
  autoreplied boolean NOT NULL DEFAULT false,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messaging_unrouted_inbound_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenant_text_balance (
  tenant_id uuid NOT NULL,
  month text NOT NULL CHECK (month ~ '^[0-9]{4}-[0-9]{2}$'::text),
  month_used integer NOT NULL DEFAULT 0 CHECK (month_used >= 0),
  pack_balance integer NOT NULL DEFAULT 0 CHECK (pack_balance >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenant_text_balance_pkey PRIMARY KEY (tenant_id),
  CONSTRAINT tenant_text_balance_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.text_pack_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  pack_key text NOT NULL CHECK (pack_key = ANY (ARRAY['texts_250'::text, 'texts_1000'::text])),
  texts integer NOT NULL CHECK (texts > 0),
  amount_pence integer NOT NULL CHECK (amount_pence >= 0),
  currency text NOT NULL DEFAULT 'gbp'::text,
  stripe_checkout_session_id text NOT NULL UNIQUE,
  stripe_payment_intent_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT text_pack_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT text_pack_purchases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.visit_changes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['skip'::text, 'reschedule'::text, 'move_remaining'::text, 'skip_remaining'::text])),
  from_date date,
  to_date date,
  job_ids ARRAY NOT NULL CHECK (cardinality(job_ids) >= 1),
  before jsonb NOT NULL CHECK (jsonb_typeof(before) = 'array'::text),
  notify_customers boolean NOT NULL DEFAULT false,
  notified_at timestamp with time zone,
  created_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  undone_at timestamp with time zone,
  undone_by_user_id uuid,
  undo_notified_at timestamp with time zone,
  CONSTRAINT visit_changes_pkey PRIMARY KEY (id),
  CONSTRAINT visit_changes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.customer_charges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  kind text NOT NULL DEFAULT 'other'::text CHECK (kind = ANY (ARRAY['starting_balance'::text, 'other'::text])),
  description text NOT NULL CHECK (char_length(btrim(description)) >= 1 AND char_length(btrim(description)) <= 120),
  amount numeric NOT NULL CHECK (amount > 0::numeric AND amount <= 100000::numeric),
  charge_date date NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'void'::text])),
  created_by_user_id uuid,
  voided_at timestamp with time zone,
  voided_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_charges_pkey PRIMARY KEY (id),
  CONSTRAINT customer_charges_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT customer_charges_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_charges_created_by_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT customer_charges_voided_by_fkey FOREIGN KEY (voided_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.owner_pushes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['card_payment'::text, 'dd_payment'::text, 'dd_failed'::text, 'dd_cancelled'::text, 'dd_active'::text, 'dd_attention'::text])),
  title text NOT NULL CHECK (char_length(title) >= 1 AND char_length(title) <= 80),
  body text NOT NULL CHECK (char_length(body) >= 1 AND char_length(body) <= 200),
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  send_after timestamp with time zone NOT NULL,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT owner_pushes_pkey PRIMARY KEY (id),
  CONSTRAINT owner_pushes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.gocardless_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'not_connected'::text CHECK (status = ANY (ARRAY['not_connected'::text, 'connected'::text, 'disconnected'::text])),
  organisation_id text,
  creditor_id text,
  access_token_enc text,
  connected_email text CHECK (connected_email IS NULL OR char_length(connected_email) <= 254),
  verification_status text CHECK (verification_status IS NULL OR (verification_status = ANY (ARRAY['successful'::text, 'in_review'::text, 'action_required'::text]))),
  verification_checked_at timestamp with time zone,
  mandates_checked_at timestamp with time zone,
  connected_at timestamp with time zone,
  disconnected_at timestamp with time zone,
  disconnect_reason text CHECK (disconnect_reason IS NULL OR char_length(disconnect_reason) <= 200),
  oauth_state_hash text,
  oauth_state_expires_at timestamp with time zone,
  oauth_from text CHECK (oauth_from IS NULL OR (oauth_from = ANY (ARRAY['web'::text, 'app'::text]))),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gocardless_connections_pkey PRIMARY KEY (id),
  CONSTRAINT gocardless_connections_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.gocardless_events (
  id text NOT NULL,
  organisation_id text,
  tenant_id uuid,
  resource_type text NOT NULL,
  action text NOT NULL,
  resource_id text,
  payload jsonb NOT NULL,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  attempts integer NOT NULL DEFAULT 0,
  last_error text CHECK (last_error IS NULL OR char_length(last_error) <= 500),
  CONSTRAINT gocardless_events_pkey PRIMARY KEY (id),
  CONSTRAINT gocardless_events_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.customer_direct_debits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  gocardless_organisation_id text NOT NULL,
  gocardless_billing_request_id text,
  gocardless_customer_id text,
  gocardless_mandate_id text,
  source text NOT NULL DEFAULT 'workwise'::text CHECK (source = ANY (ARRAY['workwise'::text, 'imported'::text])),
  status text NOT NULL DEFAULT 'setting_up'::text CHECK (status = ANY (ARRAY['setting_up'::text, 'pending'::text, 'active'::text, 'inactive'::text, 'cancelled'::text])),
  bank_name text,
  account_number_ending text CHECK (account_number_ending IS NULL OR account_number_ending ~ '^[0-9]{2}$'::text),
  mandate_reference text,
  next_possible_charge_date date,
  other_collections_confirmed_at timestamp with time zone,
  cancelled_by text CHECK (cancelled_by IS NULL OR (cancelled_by = ANY (ARRAY['customer'::text, 'trader'::text, 'bank'::text]))),
  inactive_reason text,
  activated_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_direct_debits_pkey PRIMARY KEY (id),
  CONSTRAINT customer_direct_debits_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT customer_direct_debits_customer_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.direct_debit_collections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  direct_debit_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount >= 1::numeric AND amount <= 1000::numeric),
  status text NOT NULL DEFAULT 'creating'::text CHECK (status = ANY (ARRAY['creating'::text, 'processing'::text, 'succeeded'::text, 'failed'::text, 'error'::text, 'cancelled'::text])),
  created_by text NOT NULL CHECK (created_by = ANY (ARRAY['cron'::text, 'trader'::text])),
  created_by_user_id uuid,
  gocardless_payment_id text,
  gocardless_status text,
  charge_date date,
  failure_code text,
  failure_message text,
  resolution text,
  resolved_at timestamp with time zone,
  resolved_by_user_id uuid,
  payment_id uuid,
  submitted_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT direct_debit_collections_pkey PRIMARY KEY (id),
  CONSTRAINT direct_debit_collections_customer_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT direct_debit_collections_dd_fkey FOREIGN KEY (direct_debit_id) REFERENCES public.customer_direct_debits(id),
  CONSTRAINT direct_debit_collections_payment_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT direct_debit_collections_created_by_user_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT direct_debit_collections_resolved_by_fkey FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id),
  CONSTRAINT direct_debit_collections_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.gocardless_mandate_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  gocardless_organisation_id text NOT NULL,
  gocardless_mandate_id text NOT NULL,
  gocardless_customer_id text,
  mandate_status text NOT NULL,
  mandate_reference text,
  mandate_created_at timestamp with time zone,
  payer_name text,
  payer_email text,
  payer_postcode text,
  bank_name text,
  account_number_ending text CHECK (account_number_ending IS NULL OR account_number_ending ~ '^[0-9]{2}$'::text),
  other_collections integer NOT NULL DEFAULT 0 CHECK (other_collections >= 0),
  other_collections_detail text,
  match_kind text NOT NULL DEFAULT 'none'::text CHECK (match_kind = ANY (ARRAY['email'::text, 'name_postcode'::text, 'none'::text])),
  suggested_customer_id uuid,
  decision text NOT NULL DEFAULT 'pending'::text CHECK (decision = ANY (ARRAY['pending'::text, 'linked'::text, 'ignored'::text])),
  linked_customer_id uuid,
  direct_debit_id uuid,
  decided_at timestamp with time zone,
  decided_by_user_id uuid,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gocardless_mandate_links_pkey PRIMARY KEY (id),
  CONSTRAINT gocardless_mandate_links_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT gocardless_mandate_links_suggested_fkey FOREIGN KEY (suggested_customer_id) REFERENCES public.customers(id),
  CONSTRAINT gocardless_mandate_links_linked_fkey FOREIGN KEY (linked_customer_id) REFERENCES public.customers(id),
  CONSTRAINT gocardless_mandate_links_dd_fkey FOREIGN KEY (direct_debit_id) REFERENCES public.customer_direct_debits(id),
  CONSTRAINT gocardless_mandate_links_user_fkey FOREIGN KEY (decided_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.gocardless_pay_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  invoice_id uuid,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['pay_by_bank'::text, 'pay_and_dd'::text])),
  amount numeric NOT NULL CHECK (amount >= 1::numeric AND amount <= 5000::numeric),
  status text NOT NULL DEFAULT 'started'::text CHECK (status = ANY (ARRAY['started'::text, 'fulfilled'::text, 'paid'::text, 'failed'::text, 'cancelled'::text])),
  gocardless_organisation_id text NOT NULL,
  gocardless_billing_request_id text NOT NULL UNIQUE,
  gocardless_payment_id text,
  direct_debit_id uuid,
  payment_id uuid,
  failure_message text CHECK (failure_message IS NULL OR char_length(failure_message) <= 300),
  fulfilled_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gocardless_pay_requests_pkey PRIMARY KEY (id),
  CONSTRAINT gocardless_pay_requests_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT gocardless_pay_requests_customer_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT gocardless_pay_requests_invoice_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT gocardless_pay_requests_dd_fkey FOREIGN KEY (direct_debit_id) REFERENCES public.customer_direct_debits(id),
  CONSTRAINT gocardless_pay_requests_payment_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);