-- Phase 2 (payments), file 2 of 4. Paste after 20260925100000, before 20260925100200.
--
-- 1. customers: "send an invoice after each visit" (payment_terms 'invoice'),
--    a stable pay-link token, and a unique payment reference.
-- 2. payments: every amount received, from any source. Voided, never deleted.
-- 3. payment_allocations: which visits each payment paid off. Written ONLY by
--    recompute_customer_payments() (file 4); clients cannot write it.
-- 4. notifications: a unique index so a visit's "visit done" email can only
--    ever be claimed once.

-- ---------------------------------------------------------------------------
-- 1. customers

-- 'monthly_invoice' was the Phase 1 spelling. Invoices are not monthly: the
-- flag means "send this customer an invoice after each visit". Both spellings
-- stay allowed so a web build still in flight during the deploy cannot fail a
-- save; the app writes 'invoice' and reads either as invoice.
ALTER TABLE public.customers DROP CONSTRAINT IF EXISTS customers_payment_terms_check;
ALTER TABLE public.customers
  ADD CONSTRAINT customers_payment_terms_check CHECK (
    payment_terms IN ('on_the_day', 'invoice', 'monthly_invoice')
  );

UPDATE public.customers SET payment_terms = 'invoice' WHERE payment_terms = 'monthly_invoice';

COMMENT ON COLUMN public.customers.payment_terms IS
  '''invoice'' = send an invoice after each visit (remembered from the Done screen). ''on_the_day'' = no invoice. ''monthly_invoice'' = legacy spelling of invoice.';

-- Random, unguessable token for https://<app>/pay/<token>. Stable: the same
-- link works in every message. Generated by the app on first need.
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS pay_link_token text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_customers_pay_link_token
  ON public.customers (pay_link_token)
  WHERE pay_link_token IS NOT NULL;

-- bank_reference_hint holds the reference printed on the pay page and
-- invoices (e.g. SMITH12). One per customer, unique within the business,
-- ignoring case, so a bank transfer reference points at exactly one customer.
CREATE UNIQUE INDEX IF NOT EXISTS uq_customers_tenant_bank_reference
  ON public.customers (tenant_id, upper(bank_reference_hint))
  WHERE bank_reference_hint IS NOT NULL;

COMMENT ON COLUMN public.customers.bank_reference_hint IS
  'Payment reference shown to the customer (e.g. SMITH12). Unique per tenant, case-insensitive. Phase 4 bank matching treats a match as a strong hint.';

-- ---------------------------------------------------------------------------
-- 2. payments

CREATE TABLE IF NOT EXISTS public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  amount numeric(10,2) NOT NULL,
  method text NOT NULL,
  source text NOT NULL DEFAULT 'manual',
  status text NOT NULL DEFAULT 'active',
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  note text,
  -- "This money was for this visit" (Stop screen / Done dialog). The engine
  -- pays this visit first; anything left over pays older visits or is credit.
  applies_to_job_id uuid,
  -- Paid against an invoice (invoice link / card on invoice). FK added in file 3.
  invoice_id uuid,
  recorded_by_user_id uuid,
  -- Phone outbox idempotency key: a replayed LOG_PAYMENT / COMPLETE_VISIT hits
  -- this unique constraint instead of recording the money twice.
  client_mutation_id text,
  -- Stripe (source = 'stripe'): written by the Connect webhook only.
  stripe_payment_intent_id text,
  stripe_checkout_session_id text,
  stripe_charge_id text,
  refunded_amount numeric(10,2) NOT NULL DEFAULT 0,
  disputed_at timestamp with time zone,
  dispute_status text,
  -- Phase 4 (source = 'open_banking'): FK to bank_transactions added then.
  bank_transaction_id uuid,
  voided_at timestamp with time zone,
  voided_by_user_id uuid,
  void_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers(id) ON DELETE CASCADE,
  CONSTRAINT payments_applies_to_job_id_fkey FOREIGN KEY (applies_to_job_id)
    REFERENCES public.jobs(id) ON DELETE SET NULL,
  CONSTRAINT payments_recorded_by_user_id_fkey FOREIGN KEY (recorded_by_user_id)
    REFERENCES public.users(id) ON DELETE SET NULL,
  CONSTRAINT payments_voided_by_user_id_fkey FOREIGN KEY (voided_by_user_id)
    REFERENCES public.users(id) ON DELETE SET NULL,
  CONSTRAINT payments_client_mutation_id_key UNIQUE (client_mutation_id),
  CONSTRAINT payments_stripe_payment_intent_id_key UNIQUE (stripe_payment_intent_id),
  CONSTRAINT payments_stripe_checkout_session_id_key UNIQUE (stripe_checkout_session_id),
  CONSTRAINT payments_bank_transaction_id_key UNIQUE (bank_transaction_id),
  CONSTRAINT payments_amount_check CHECK (amount > 0 AND amount <= 100000),
  CONSTRAINT payments_method_check CHECK (
    method IN ('cash', 'cheque', 'bank_transfer', 'card', 'other')
  ),
  CONSTRAINT payments_source_check CHECK (source IN ('manual', 'stripe', 'open_banking')),
  CONSTRAINT payments_status_check CHECK (status IN ('active', 'void')),
  CONSTRAINT payments_refunded_check CHECK (refunded_amount >= 0 AND refunded_amount <= amount),
  CONSTRAINT payments_note_check CHECK (note IS NULL OR char_length(note) <= 300),
  CONSTRAINT payments_void_reason_check CHECK (void_reason IS NULL OR char_length(void_reason) <= 300),
  CONSTRAINT payments_void_consistency_check CHECK (
    (status = 'void') = (voided_at IS NOT NULL)
  )
);

COMMENT ON TABLE public.payments IS
  'Money received from a customer. Never deleted: undo = status void. Allocation to visits is derived by recompute_customer_payments().';

CREATE INDEX IF NOT EXISTS idx_payments_tenant_customer
  ON public.payments (tenant_id, customer_id, received_at);
CREATE INDEX IF NOT EXISTS idx_payments_tenant_received
  ON public.payments (tenant_id, received_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_applies_to_job
  ON public.payments (applies_to_job_id)
  WHERE applies_to_job_id IS NOT NULL;

DROP TRIGGER IF EXISTS payments_set_updated_at ON public.payments;
CREATE TRIGGER payments_set_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payments_tenant_select" ON public.payments;
DROP POLICY IF EXISTS "payments_admin_insert" ON public.payments;
DROP POLICY IF EXISTS "payments_admin_void" ON public.payments;

CREATE POLICY "payments_tenant_select"
ON public.payments FOR SELECT
TO authenticated
USING (
  tenant_id IN (SELECT tenant_id FROM public.users WHERE id = auth.uid())
  OR tenant_id IN (SELECT primary_tenant_id FROM public.workers WHERE user_id = auth.uid())
);

-- Manual payments only. Stripe and open-banking payments are inserted by the
-- service role (webhook / bank sync), which bypasses RLS.
CREATE POLICY "payments_admin_insert"
ON public.payments FOR INSERT
TO authenticated
WITH CHECK (
  tenant_id IN (SELECT tenant_id FROM public.users WHERE id = auth.uid() AND role = 'admin')
  AND source = 'manual'
  AND status = 'active'
  AND customer_id IN (SELECT c.id FROM public.customers c WHERE c.tenant_id = payments.tenant_id)
);

-- The only client update allowed: voiding an active manual payment.
CREATE POLICY "payments_admin_void"
ON public.payments FOR UPDATE
TO authenticated
USING (
  tenant_id IN (SELECT tenant_id FROM public.users WHERE id = auth.uid() AND role = 'admin')
  AND source = 'manual'
  AND status = 'active'
)
WITH CHECK (
  tenant_id IN (SELECT tenant_id FROM public.users WHERE id = auth.uid() AND role = 'admin')
  AND status = 'void'
);

REVOKE ALL ON public.payments FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.payments FROM authenticated;
GRANT SELECT ON public.payments TO authenticated;
GRANT INSERT (
  tenant_id, customer_id, amount, method, received_at, note,
  applies_to_job_id, invoice_id, recorded_by_user_id, client_mutation_id
) ON public.payments TO authenticated;
GRANT UPDATE (status, voided_at, voided_by_user_id, void_reason)
  ON public.payments TO authenticated;

-- ---------------------------------------------------------------------------
-- 3. payment_allocations (derived; engine-written only)

CREATE TABLE IF NOT EXISTS public.payment_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  payment_id uuid NOT NULL,
  job_id uuid NOT NULL,
  amount numeric(10,2) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT payment_allocations_tenant_id_fkey FOREIGN KEY (tenant_id)
    REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT payment_allocations_payment_id_fkey FOREIGN KEY (payment_id)
    REFERENCES public.payments(id) ON DELETE CASCADE,
  CONSTRAINT payment_allocations_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.jobs(id) ON DELETE CASCADE,
  CONSTRAINT payment_allocations_payment_job_key UNIQUE (payment_id, job_id),
  CONSTRAINT payment_allocations_amount_check CHECK (amount > 0)
);

COMMENT ON TABLE public.payment_allocations IS
  'Which visits a payment paid off. Rebuilt from scratch per customer by recompute_customer_payments(); never written by the app.';

CREATE INDEX IF NOT EXISTS idx_payment_allocations_job_id
  ON public.payment_allocations (job_id);

ALTER TABLE public.payment_allocations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payment_allocations_tenant_select" ON public.payment_allocations;

CREATE POLICY "payment_allocations_tenant_select"
ON public.payment_allocations FOR SELECT
TO authenticated
USING (
  tenant_id IN (SELECT tenant_id FROM public.users WHERE id = auth.uid())
  OR tenant_id IN (SELECT primary_tenant_id FROM public.workers WHERE user_id = auth.uid())
);

REVOKE ALL ON public.payment_allocations FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.payment_allocations FROM authenticated;
GRANT SELECT ON public.payment_allocations TO authenticated;

-- ---------------------------------------------------------------------------
-- 4. notifications: one "visit done" message per visit, ever.
-- The app inserts a 'pending' row BEFORE sending; a second attempt (offline
-- replay, double tap, retry) hits this index with 23505 and does not send.
CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_visit_done
  ON public.notifications (job_id, type)
  WHERE type = 'visit_done' AND job_id IS NOT NULL;
