-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_interactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  interaction_type text NOT NULL CHECK (interaction_type = ANY (ARRAY['skill_detection'::text, 'quote_generation'::text, 'column_mapping'::text, 'worker_interview_parsing'::text, 'value_transformation'::text])),
  input_prompt text NOT NULL,
  input_data jsonb NOT NULL,
  ai_response text NOT NULL,
  parsed_output jsonb,
  model text NOT NULL,
  provider text NOT NULL DEFAULT 'anthropic'::text,
  tokens_input integer,
  tokens_output integer,
  tokens_total integer,
  latency_ms integer,
  cost_usd numeric,
  user_edited boolean DEFAULT false,
  user_rating integer CHECK (user_rating >= 1 AND user_rating <= 5),
  accepted boolean DEFAULT true,
  edit_details jsonb,
  actual_outcome jsonb,
  accuracy_score numeric,
  job_id uuid,
  worker_id uuid,
  import_source_id uuid,
  quote_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_agent text,
  ip_address inet,
  environment text DEFAULT 'production'::text CHECK (environment = ANY (ARRAY['production'::text, 'staging'::text, 'development'::text])),
  CONSTRAINT ai_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_interactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT ai_interactions_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT ai_interactions_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT ai_interactions_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id)
);
CREATE TABLE public.ai_model_performance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  model_type text NOT NULL CHECK (model_type = ANY (ARRAY['claude_api'::text, 'custom_skill_classifier'::text, 'custom_quote_estimator'::text, 'hybrid'::text])),
  model_version text NOT NULL,
  total_predictions integer DEFAULT 0,
  correct_predictions integer DEFAULT 0,
  accuracy numeric,
  precision_score numeric,
  recall_score numeric,
  f1_score numeric,
  total_cost_usd numeric,
  avg_cost_per_prediction numeric,
  avg_latency_ms integer,
  avg_user_rating numeric,
  edit_rate numeric,
  acceptance_rate numeric,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT ai_model_performance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_training_datasets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  dataset_type text NOT NULL CHECK (dataset_type = ANY (ARRAY['skill_detection'::text, 'quote_estimation'::text, 'pricing_optimization'::text, 'worker_matching'::text, 'full_export'::text])),
  version text NOT NULL,
  examples_count integer NOT NULL,
  training_split numeric DEFAULT 0.80,
  validation_split numeric DEFAULT 0.10,
  test_split numeric DEFAULT 0.10,
  quality_score numeric,
  human_reviewed_count integer DEFAULT 0,
  accuracy_threshold numeric,
  file_path text,
  file_size_bytes bigint,
  file_format text DEFAULT 'jsonl'::text CHECK (file_format = ANY (ARRAY['jsonl'::text, 'csv'::text, 'parquet'::text])),
  trained_model_id uuid,
  training_started_at timestamp with time zone,
  training_completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  notes text,
  tags ARRAY,
  CONSTRAINT ai_training_datasets_pkey PRIMARY KEY (id),
  CONSTRAINT ai_training_datasets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  name text NOT NULL,
  contact_person text,
  email text,
  phone text,
  type USER-DEFINED NOT NULL DEFAULT 'individual'::customer_type,
  company_name text,
  billing_address text,
  portal_token text UNIQUE,
  portal_last_accessed_at timestamp with time zone,
  total_jobs integer DEFAULT 0,
  last_job_date date,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.import_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  import_source_id uuid,
  file_name text NOT NULL,
  file_size_bytes integer,
  rows_total integer NOT NULL,
  rows_imported integer NOT NULL,
  rows_failed integer DEFAULT 0,
  job_ids ARRAY,
  errors jsonb DEFAULT '[]'::jsonb,
  imported_by_user_id uuid,
  started_at timestamp with time zone NOT NULL,
  completed_at timestamp with time zone,
  duration_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT import_history_pkey PRIMARY KEY (id),
  CONSTRAINT import_history_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT import_history_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id),
  CONSTRAINT import_history_imported_by_user_id_fkey FOREIGN KEY (imported_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.import_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  source_name text NOT NULL,
  source_identifier text,
  column_mapping jsonb NOT NULL,
  mapped_by text DEFAULT 'manual'::text,
  ai_confidence numeric,
  last_used_at timestamp with time zone,
  times_used integer DEFAULT 0,
  required_columns ARRAY,
  default_values jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT import_sources_pkey PRIMARY KEY (id),
  CONSTRAINT import_sources_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.job_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size_bytes integer,
  attachment_type text NOT NULL DEFAULT 'other'::text,
  caption text,
  uploaded_by_worker_id uuid,
  uploaded_by_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT job_attachments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_attachments_uploaded_by_worker_id_fkey FOREIGN KEY (uploaded_by_worker_id) REFERENCES public.workers(id),
  CONSTRAINT job_attachments_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.job_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  from_status USER-DEFINED,
  to_status USER-DEFINED NOT NULL,
  changed_by_user_id uuid,
  changed_by_worker_id uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT job_status_history_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_status_history_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT job_status_history_changed_by_worker_id_fkey FOREIGN KEY (changed_by_worker_id) REFERENCES public.workers(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  reference_number text NOT NULL,
  customer_id uuid,
  assigned_worker_id uuid,
  import_source_id uuid,
  address text NOT NULL,
  postcode text NOT NULL,
  lat numeric,
  lng numeric,
  job_description text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::job_status,
  priority USER-DEFINED NOT NULL DEFAULT 'normal'::job_priority,
  scheduled_date date,
  scheduled_time time without time zone,
  estimated_duration_minutes integer,
  started_at timestamp with time zone,
  arrived_at timestamp with time zone,
  completed_at timestamp with time zone,
  industry_data jsonb DEFAULT '{}'::jsonb,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  quoted_amount numeric,
  final_amount numeric,
  completion_notes text,
  customer_signature_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  required_skills jsonb DEFAULT '[]'::jsonb,
  auto_assign_failure_reason text,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT jobs_assigned_worker_id_fkey FOREIGN KEY (assigned_worker_id) REFERENCES public.workers(id),
  CONSTRAINT jobs_import_source_id_fkey FOREIGN KEY (import_source_id) REFERENCES public.import_sources(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  recipient_type text NOT NULL,
  recipient_id uuid,
  recipient_email text,
  recipient_phone text,
  type text NOT NULL,
  channel text NOT NULL,
  subject text,
  body text NOT NULL,
  job_id uuid,
  status text DEFAULT 'pending'::text,
  sent_at timestamp with time zone,
  failed_reason text,
  provider text,
  provider_message_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT notifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  industry text,
  settings jsonb DEFAULT '{}'::jsonb,
  subscription_status text DEFAULT 'active'::text,
  subscription_tier text DEFAULT 'standard'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  tenant_id uuid,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'admin'::text,
  avatar_url text,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.worker_tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid,
  tenant_id uuid,
  status text DEFAULT 'active'::text,
  is_primary boolean DEFAULT false,
  commission_rate numeric,
  hourly_rate numeric,
  jobs_completed integer DEFAULT 0,
  average_rating numeric,
  added_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT worker_tenants_pkey PRIMARY KEY (id),
  CONSTRAINT worker_tenants_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.workers(id),
  CONSTRAINT worker_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.workers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  phone text NOT NULL,
  email text,
  avatar_url text,
  worker_type USER-DEFINED NOT NULL DEFAULT 'company_subcontractor'::worker_type,
  primary_tenant_id uuid,
  home_postcode text,
  home_lat numeric,
  home_lng numeric,
  service_radius_km integer DEFAULT 50,
  skills jsonb DEFAULT '[]'::jsonb,
  certifications jsonb DEFAULT '[]'::jsonb,
  status USER-DEFINED DEFAULT 'available'::worker_status,
  total_jobs_completed integer DEFAULT 0,
  average_rating numeric,
  total_reviews integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expo_push_token text,
  invite_status text DEFAULT 'pending'::text,
  CONSTRAINT workers_pkey PRIMARY KEY (id),
  CONSTRAINT workers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workers_primary_tenant_id_fkey FOREIGN KEY (primary_tenant_id) REFERENCES public.tenants(id)
);